#!/bin/sh
#to run: run_sim <Trace> <config>
#Configs are
# BASE 0 L12WAY 1 L22WAY 2 ALL2WAY 3 L12WAYL24WAY 4 L2BIG 5 ALLFA 6 

cat short-traces/$1 | Debug/CacheSim $2 $3 1>Results_New/S/$1_config_$2.txt
